const CONFIG = {
    introTitle: '"Annie"',
    introDesc: `Một điều sến rện trong mùa dịch`,
    btnIntro: '💜',
    title: 'Ai lò vé Du',
    desc: 'Du có thương Me khum',
    btnYes: 'Thưng lúm 💜',
    btnNo: 'Khum, lìu liu 😂',
    title: 'Dạo này bận quá nhưng khum sao vẫn có thời gian rãnh để tặng em cái thứ sến rện này 😉',
    question: 'Sau dịch muốn đi ăn gì',
    btnReply: 'Quăng dô đây',
    reply: 'Ăn vặt, ún trà sữa        ',
    mess: 'Hết gòi, sến vậy đủ gòi 😁',
    messDesc: 'Ráng đợi hết dịch nhé',
    btnAccept: 'Kê lun ❤',
}
